---
title: Test the likelihood calculation integrated across all partiions within a marker
  group for a given subtype
output:
  pdf_document: default
  html_notebook: default
---

# Preliminaries

```{r}
setwd("/Users/chwu/Documents/research/bfc/github/Forensic-Fluids/")
source("forensicFunctions.R")
```

```{r}
library(salso)
```

```{r}

load("allParts5And7EltsMatsAndSets.rda")

singleTypeFilePath = "data.csv"
single.df = read.csv(singleTypeFilePath, header = TRUE) # whole single sample data
slv.df = single.df[single.df$Sample == 3,] # saliva
dim(slv.df)

sample.df = slv.df[,-1] # single sample data, delete the index column
dim(sample.df)
```

# Partition with three elements

```{r}
enumerate.partitions(3)
# [,1] [,2] [,3]
# [1,]    1    1    1
# [2,]    1    1    2
# [3,]    1    2    1
# [4,]    1    2    2
# [5,]    1    2    3
```

```{r}
set.seed(222)
kmeansClust3Index = c(1, 3, 1, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2, 1, 
                      3, 2, 3, 1, 2, 2, 2, 2, 2, 3, 2, 3, 2, 1, 2, 3, 2, 1, 
                      2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1, 1, 1, 2, 2, 
                      3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 3, 3, 1, 2, 
                      1, 1, 1, 1, 1, 1, 3, 3, 1)
slvClust1ExIndx = sample(which(kmeansClust3Index==1), 2)
# 180 183 
#  75  78
slvClust2ExIndx = sample(which(kmeansClust3Index==2), 5)
# 146 147 145 121 122 
#  41  42  40  16  17 
slvClust3ExIndx = sample(which(kmeansClust3Index==3), 3)
# 185 162 126 
#  80  57  21

rowExIndx = c(slvClust1ExIndx, slvClust2ExIndx, slvClust3ExIndx)
sample.df[rowExIndx ,1:5]



colExIndx = c(1,2,5)
slvEx1.df = sample.df[rowExIndx, c("CYP", "HBD1", "MUC4")]
rowSums(slvEx1.df)
colSums(slvEx1.df)

prod(dim(slvEx1.df))
sum(slvEx1.df)
prod(dim(slvEx1.df)) - sum(slvEx1.df)
```

```{r}
# 1    1    1
prod(dim(slvEx1.df))
sum(slvEx1.df)
prod(dim(slvEx1.df)) - sum(slvEx1.df)

exp(sum(log(1:9)) - sum(log(25:34)))
```

```{r}
calcLikIntAllPart(eltsAllPartSet = list(list(c(1, 2, 3))), 
                             sample = slvEx1.df, 
                             alphaC = 2, 
                             betaC = 3)
```

```{r}
# 1    1    2
prod(dim(slvEx1.df[, 1:2]))
sum(slvEx1.df[, 1:2])
prod(dim(slvEx1.df[, 1:2])) - sum(slvEx1.df[, 1:2])

length(slvEx1.df[, 3])
sum(slvEx1.df[, 3])

length(slvEx1.df[, 3]) - sum(slvEx1.df[, 3])

exp((sum(log(1:4)) - sum(log(20:24))))*exp((sum(log(1:6)) - sum(log(8:14))))

calcLikIntAllPart(eltsAllPartSet = list(list(c(1, 2), c(3))), 
                  sample = slvEx1.df, 
                  alphaC = 2, 
                  betaC = 3)
```

```{r}
# 1    2    1
prod(dim(slvEx1.df[, c(1,3)]))
sum(slvEx1.df[, c(1,3)])
length(slvEx1.df[, 2]) - sum(slvEx1.df[, 2])

expt3 = exp((sum(log(1:7)) - sum(log(17:24))))*exp((sum(log(1:3)) - sum(log(11:14))))
ans3 = calcLikIntAllPart(eltsAllPartSet = list(list(c(1, 3), c(2))), 
                  sample = slvEx1.df, 
                  alphaC = 2, 
                  betaC = 3)
expt3 - ans3
```

```{r}
# 1    2    2
length(slvEx1.df[, 1])
sum(slvEx1.df[, 1])
prod(dim(slvEx1.df[, c(2,3)]))
sum(slvEx1.df[, c(2,3)])
```

```{r}

expt4 = exp(-sum(log(c(6, 13, 14))))*exp((sum(log(1:8)) - sum(log(16:24))))
ans4 = calcLikIntAllPart(eltsAllPartSet = list(list(c(1), c(2, 3))), 
                         sample = slvEx1.df, 
                         alphaC = 2, 
                         betaC = 3)
expt4 - ans4
```

```{r}
# 1    2    3
length(slvEx1.df[, 1])
sum(slvEx1.df[, 1])
length(slvEx1.df[, 2])
sum(slvEx1.df[, 2])
length(slvEx1.df[, 3])
sum(slvEx1.df[, 3])
```

```{r}

expt5 = exp(-sum(log(c(6, 13, 14))))*exp(-sum(log(c(2, 11, 13, 14))))*
  exp(sum(log(1:6))-sum(log(c(8:14))))
ans5 = calcLikIntAllPart(eltsAllPartSet = list(list(c(1), c(2), c(3))), 
                         sample = slvEx1.df, 
                         alphaC = 2, 
                         betaC = 3)
expt5 - ans5
```

# Partition with four elements

```{r}
enumerate.partitions(4)
#       [,1] [,2] [,3] [,4]
#  [1,]    1    1    1    1
#  [2,]    1    1    1    2
#  [3,]    1    1    2    1
#  [4,]    1    1    2    2
#  [5,]    1    1    2    3
#  [6,]    1    2    1    1
#  [7,]    1    2    1    2
#  [8,]    1    2    1    3
#  [9,]    1    2    2    1
# [10,]    1    2    2    2
# [11,]    1    2    2    3
# [12,]    1    2    3    1
# [13,]    1    2    3    2
# [14,]    1    2    3    3
# [15,]    1    2    3    4
```

```{r}
set.seed(123)
slvClust1ExIndx2 = sample(which(kmeansClust3Index==1), 2)
slvClust2ExIndx2 = sample(which(kmeansClust3Index==2), 5)
slvClust3ExIndx2 = sample(which(kmeansClust3Index==3), 3)
```

```{r}
rowExIndx2 = c(slvClust1ExIndx2, slvClust2ExIndx2, slvClust3ExIndx2)
slvEx2.df = sample.df[rowExIndx2 ,c("HTN3", "MUC7", "PRB4", "SMR3B" )]
slvEx2.df
```

## Partition 1

```{r ex1_part1_clust1}
sum(slvEx2.df)
prod(dim(slvEx2.df))
```


```{r}
ex2.expt1 = sum(log(1:13)) - sum(log(31:44))
ex2.ans1 = log(calcLikIntAllPart(eltsAllPartSet = list(list(c(1:4))), 
                         sample = slvEx2.df, 
                         alphaC = 3, 
                         betaC = 2))

print(ex2.expt1, digit = 12)
print(ex2.ans1, digit = 12)

ex2.expt1 - ex2.ans1 
all(abs(ex2.expt1 - ex2.ans1) < 1e-10)
```

## Partition 2

Partition pattern: (1, 1, 1, 2)

```{r ex2_part2_clust1}
sum(slvEx2.df[, 1:3])
prod(dim(slvEx2.df[, 1:3]))
```


```{r ex2_part2_clust2}
sum(slvEx2.df[,4])
length(slvEx2.df[,4])
```

```{r ex2_part2_calc_lik}
ex2.expt2.clust1.log.lik = sum(log(1:12)) - sum(log(22:34))
ex2.expt2.clust2.log.lik = -(log(6) + log(13) + log(14))

ex2.expt2 = ex2.expt2.clust1.log.lik + ex2.expt2.clust2.log.lik
ex2.ans2 = log(calcLikIntAllPart(eltsAllPartSet = list(list(c(1:3), c(4))), 
                         sample = slvEx2.df, 
                         alphaC = 3, 
                         betaC = 2))

print(ex2.expt2, digit = 12)
print(ex2.ans2, digit = 12)

ex2.expt2 - ex2.ans2
all(abs(ex2.expt2 - ex2.ans2) < 1e-10)
```

## Partition 3

Partition pattern: (1, 1, 2, 1)

```{r ex2_part3_clust1}
sum(slvEx2.df[, c(1, 2, 4)])
prod(dim(slvEx2.df[, c(1, 2, 4)]))
```


```{r ex2_part3_clust2}
sum(slvEx2.df[,3])
length(slvEx2.df[,3])
```

```{r ex2_part3_calc_lik}
ex2.expt3.clust1.log.lik = sum(log(1:5)) - sum(log(29:34))
ex2.expt3.clust2.log.lik = -(log(5) + log(11) + log(13) + log(14))

ex2.expt3 = ex2.expt3.clust1.log.lik + ex2.expt3.clust2.log.lik
ex2.ans3 = log(calcLikIntAllPart(eltsAllPartSet = list(list(c(1,2,4), c(3))), 
                         sample = slvEx2.df, 
                         alphaC = 3, 
                         betaC = 2))

print(ex2.expt3, digit = 12)
print(ex2.ans3, digit = 12)

ex2.expt3 - ex2.ans3
all(abs(ex2.expt3 - ex2.ans3) < 1e-10)
```

## Partition 4

Partition pattern: (1, 1, 2, 2)

```{r ex2_part4_clust1}
sum(slvEx2.df[, c(1, 2)])
prod(dim(slvEx2.df[, c(1, 2)]))
```


```{r ex2_part4_clust2}
sum(slvEx2.df[, c(3, 4)])
prod(dim(slvEx2.df[, c(3, 4)]))
```

```{r ex2_part4_calc_lik}
ex2.expt4.clust1.log.lik = - sum(log(20:23))
ex2.expt4.clust2.log.lik = sum(log(1:10)) - sum(log(14:24))

ex2.expt4 = ex2.expt4.clust1.log.lik + ex2.expt4.clust2.log.lik
ex2.ans4 = log(calcLikIntAllPart(eltsAllPartSet = list(list(c(1,2), c(3,4))), 
                         sample = slvEx2.df, 
                         alphaC = 3, 
                         betaC = 2))

print(ex2.expt4, digit = 12)
print(ex2.ans4, digit = 12)

ex2.expt4 - ex2.ans4
all(abs(ex2.expt4 - ex2.ans4) < 1e-10)
```


## Partition 5

Partition pattern: (1, 1, 2, 2)

```{r ex2_part5_clust1}
sum(slvEx2.df[, c(1, 2)])
prod(dim(slvEx2.df[, c(1, 2)]))
```


```{r ex2_part5_clust2}
sum(slvEx2.df[, 3])
length(slvEx2.df[, 3])
```

```{r ex2_part5_clust3}
sum(slvEx2.df[, 4])
length(slvEx2.df[,4])
```

```{r ex2_part5_calc_lik}
ex2.expt5.clust1.log.lik = - sum(log(20:23))
ex2.expt5.clust2.log.lik = - sum(log(c(5, 11, 13, 14)))
ex2.expt5.clust3.log.lik = - sum(log(c(6, 13, 14)))

ex2.expt5 = ex2.expt5.clust1.log.lik + ex2.expt5.clust2.log.lik + ex2.expt5.clust3.log.lik
ex2.ans5 = log(calcLikIntAllPart(eltsAllPartSet = list(list(c(1,2), c(3), c(4))), 
                         sample = slvEx2.df, 
                         alphaC = 3, 
                         betaC = 2))

print(ex2.expt5, digit = 12)
print(ex2.ans5, digit = 12)

ex2.expt5 - ex2.ans5
all(abs(ex2.expt5 - ex2.ans5) < 1e-10)
```